### ISSUE TITLE
Entrevista 

### ISSUE THREAD

**Issue by mel-16** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-de-melissa#1]
[Entrevista contestada.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-equipo-de-melissa/files/9492158/Entrevista.contestada.pdf)

**Comment by EdwinOrtiz1412** [comment]
Calificación: 15

**Comment by josealfredo79** [comment]
Revisado...
